name: Retag and Push Manifest

inputs:
  token:
    description: "Session token"
    default: ""
    type: string
  container:
    description: "The container to build"
    required: true
    type: string
  tag-input:
    description: "Input tag"
    required: true
    type: string
  tag-output:
    description: "Output tag"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      if: inputs.token != ''
      with:
        registry: ghcr.io
        username: concordia-fsae
        password: ${{ inputs.token }}
    - name: Pull Images
      shell: bash
      run: |
        docker pull ghcr.io/concordia-fsae/containers/${{ inputs.containert }}:${{ inputs.tag-input }}
    - name: Retag Images and Push
      shell: bash
      run: |
        docker tag ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag-input }} ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag-output }} && \
        docker push ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag-output }}
