name: Run an Image Build and Push

inputs:
  token:
    description: "Session token"
    default: ""
    type: string
  arch:
    description: "The architecture to build"
    required: true
    type: string
  container:
    description: "The container to build"
    required: true
    type: string
  tag-prefix:
    description: "What to prepend to '-arch'"
    required: true
    type: string
outputs:
  archive-url:
    description: "The link to the github archive of the build artifacts"
    value: ${{ steps.archive.outputs.archive-url }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      if: inputs.token != ''
      with:
        registry: ghcr.io
        username: concordia-fsae
        password: ${{ inputs.token }}
    - name: Build Ubuntu Noble LTS
      shell: bash
      run: |
        docker buildx build ${{ inputs.container }} --platform linux/${{ inputs.arch }} \
        -t ghcr.io/concordia-fsae/containers/ubuntu-noble-lts:${{ inputs.tag-prefix }}-${{ inputs.arch }} \
        -o type=docker,dest=- > ${{ runner.temp }}/${{ inputs.container }}.tar
    - name: Upload Docker Image as Artifact
      id: archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.container }}-${{ inputs.arch }}
        path: ${{ runner.temp }}/${{ inputs.container }}.tar
    - name: Push Image
      shell: bash
      run: |
        docker load -i ${{ runner.temp }}/${{ inputs.container }}.tar && \
        docker push -a ghcr.io/concordia-fsae/containers/${{ inputs.container }}
