name: Create and Push Manifest

inputs:
  token:
    description: "Session token"
    default: ""
    type: string
  container:
    description: "The container to build"
    required: true
    type: string
  tag:
    description: "What to prepend to '-arch' for the input tag"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      if: inputs.token != ''
      with:
        registry: ghcr.io
        username: concordia-fsae
        password: ${{ inputs.token }}
    - name: Pull Images
      shell: bash
      run: |
        docker pull ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }}-arm64 && \
        docker pull ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }}-amd64
    - name: Create and Push Multiarch Manifest
      shell: bash
      run: |
        docker manifest create ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }} \
        --amend ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }}-arm64 \
        --amend ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }}-amd64 && \
        docker manifest push ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }} && \
        docker manifest inspect ghcr.io/concordia-fsae/containers/${{ inputs.container }}:${{ inputs.tag }}
