name: 'Build, Tag, Validate Noble LTS'

on:
  pull_request:
    branches: [ main ]

jobs:
  build-noble-lts:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.sha.outputs.short-sha }}
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Clean
        uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
      - name: Pull Branch
        uses: actions/checkout@v4
        with:
          show-progress: 'true'
          submodules: 'recursive'
      - name: Get SHA7
        id: sha
        uses: concordia-fsae/firmware/.github/actions/get-short-sha/@master
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Build Image
        id: build
        uses: concordia-fsae/containers/.github/actions/build_image/@main
        with:
          arch: ${{ matrix.arch }}
          container: ubuntu-noble-lts
          tag-prefix: ${{ steps.sha.outputs.short-sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
  build-multiarch-manifest:
    runs-on: ubuntu-latest
    needs: build-noble-lts
    steps:
      - name: Build Multiarch SHA Manifest
        uses: concordia-fsae/containers/.github/actions/create_multiarch_manifest/@main
        with:
          container: ubuntu-noble-lts
          tag: ${{ needs.build-noble-lts.outputs.short-sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
  validate-container-functionality:
    uses: concordia-fsae/firmware/.github/workflows/build.yml@master
    needs: [ build-multiarch-manifest, build-noble-lts ]
    with:
      build-type: platform
      build-targets: cfr25
      flags: -j32 --flashable-bootloader --package
      artifact-name: artifact-validation
      container: ubuntu-noble-lts:${{ needs.build-noble-lts.outputs.short-sha }}
