name: 'Build, Tag, and Push Containers'

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
      - name: Pull Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: 'true'
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.USERNAME}}
          password: ${{secrets.TOKEN}}
      - name: Build Ubuntu Noble LTS
        run: |
          docker buildx build ubuntu-noble-lts --platform linux/arm64,linux/amd64 \
          -t ghcr.io/concordia-fsae/containers/ubuntu-noble-lts:latest \
          docker push -a ghcr.io/concordia-fsae/containers/ubuntu-noble-lts
