name: 'Deploy Noble LTS to latest version'

on:
  push:
    branches: [ main ]

env:
  version: v1.0.2

jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs: 
      short-sha: ${{ steps.sha.outputs.short-sha }}
    steps:
      - name: Get SHA7
        id: sha
        uses: concordia-fsae/firmware/.github/actions/pull/@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  retag-latest:
    runs-on: ubuntu-latest
    needs: get-short-sha
    steps:
      - name: Retag
        uses: ./.github/actions/retag_push_image/
        with:
          container: ubuntu-noble-lts
          tag-input: ${{ needs.get-short-sha.outputs.short-sha }}
          tag-output: latest
          token: ${{ secrets.GITHUB_TOKEN }}
  retag-version:
    runs-on: ubuntu-latest
    needs: get-short-sha
    steps:
      - name: Retag
        uses: ./.github/actions/retag_push_image/
        with:
          container: ubuntu-noble-lts
          tag-input: ${{ needs.get-short-sha.outputs.short-sha }}
          tag-output: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
  build-multiarch-manifest-latest:
    runs-on: ubuntu-latest
    needs: retag-latest
    steps:
      - name: Build Multiarch SHA Manifest
        uses: ./.github/actions/create_multiarch_manifest/
        with:
          container: ubuntu-noble-lts
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
  build-multiarch-manifest-version:
    runs-on: ubuntu-latest
    needs: retag-version
    steps:
      - name: Build Multiarch SHA Manifest
        uses: ./.github/actions/create_multiarch_manifest/
        with:
          container: ubuntu-noble-lts
          tag: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
